CREATE DATABASE IF NOT EXISTS CAMAGRU DEFAULT CHARACTER SET utf8;

USE CAMAGRU;

CREATE TABLE IF NOT EXISTS Users (
		id SMALLINT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
		username VARCHAR(15) NOT NULL,
		mail VARCHAR(30) NOT NULL,
		password VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS Images(
		id smallint(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
		name VARCHAR(15) NOT NULL,
		username VARCHAR(50) NOT NULL,
		type VARCHAR(25) NOT NULL,
		descrip TEXT NOT NULL,
		img_blob LONGBLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS Commentary (
		id SMALLINT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
		username VARCHAR(50) NOT NULL,
		contents VARCHAR(250) NOT NULL,
		date DATETIME
);

CREATE TABLE IF NOT EXISTS Likes (
		id SMALLINT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
		userid SMALLINT(5) NOT NULL,
		imgid SMALLINT(5) NOT NULL
);