CREATE DATABASE IF NOT EXISTS CAMAGRU DEFAULT CHARACTER SET utf8;

USE CAMAGRU;

CREATE TABLE IF NOT EXISTS users (
		id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
		username VARCHAR(15) NOT NULL,
		mail VARCHAR(30) NOT NULL,
		password VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS images(
		id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
		name VARCHAR(15) NOT NULL,
		username VARCHAR(50) NOT NULL,
		type VARCHAR(25) NOT NULL,
		descrip TEXT NOT NULL,
		img_blob LONGBLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS commentary (
		id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
		userid INT(11) NOT NULL,
		imgid INT(11) NOT NULL,
		contents VARCHAR(250) NOT NULL,
		date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
		KEY (`userid`),
		KEY (`imgid`),
		CONSTRAINT `commentary_userid` FOREIGN KEY (`userid`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
		CONSTRAINT `commentary_img` FOREIGN KEY (`imgid`) REFERENCES `images` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS likes (
		id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
		userid INT(11) NOT NULL,
		imgid INT(11) NOT NULL,
		KEY (`userid`),
		KEY (`imgid`),
		CONSTRAINT `likes_userid` FOREIGN KEY (`userid`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
		CONSTRAINT `likes_img` FOREIGN KEY (`imgid`) REFERENCES `images` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);